# vim:ft=tmux
######################
### DESIGN CHANGES ###
######################

# loud or quiet?
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

#  modes
setw -g clock-mode-colour colour5
setw -g mode-style 'fg=#{theme_fg},bg=#{theme_bg},bold'

# panes
set -g pane-border-style 'fg=#{theme_fg},bg=#{theme_bg}'
set -g pane-active-border-style 'fg=#{theme_fg},bg=#{theme_bg}'

# statusbar
set -g status-position bottom
set -g status-style "bg=#{theme_bg},fg=#{theme_fg}"
set -g status-justify left
set -g status-interval 5

set -g status-left '#[fg=#{theme_primary},bg=#{theme_bg}]  #S '
set -g status-left-length 20

set -g status-right '#[fg=#{theme_fg_dim},bg=#{theme_bg}]#{pane_current_command} #[fg=#{theme_bg},bg=#{theme_primary}] #H #[fg=#{theme_primary},bg=#{theme_bg}]'
set -g status-right-length 120

setw -g window-status-current-style ''
setw -g window-status-current-format '#[bg=#{theme_primary} fg=#{theme_bg}]#[bg=#{theme_primary},fg=#{theme_bg}] #I:#W#F #[fg=#{theme_primary},bg=#{theme_bg}]'

setw -g window-status-style ''
setw -g window-status-format '#[bg=#{theme_bg} fg=#{theme_fg}] #I:#W#F '

setw -g window-status-bell-style 'fg=#{theme_fg} bg=#{theme_bg} bold'

# messages
set -g message-style 'fg=#{theme_fg} bg=#{theme_bg} bold'
