# vim:ft=tmux
######################
### DESIGN CHANGES ###
######################

# loud or quiet?
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

#  modes
setw -g clock-mode-colour colour5
setw -g mode-style 'fg=#{theme_fg},bg=#{theme_bg_dim},bold'

# panes
set -g pane-border-style 'fg=#{theme_bg_dim},bg=#{theme_bg}'
set -g pane-active-border-style 'fg=#{theme_primary},bg=#{theme_bg}'

# statusbar
set -g status-position bottom
set -g status-style "bg=#{theme_bg},fg=#{theme_fg}"
set -g status-justify left
set -g status-interval 5

set -g status-left '#[fg=#{theme_primary},bold]  #S #[default]'
set -g status-left-length 24

set -g status-right '#[fg=#{theme_fg_dim}]#{pane_current_command} #[fg=#{theme_accent}]#{b:pane_current_path} #[reverse] #{user}@#H #[default] #[fg=#{theme_fg_dim}]%H:%M '
set -g status-right-length 120

setw -g window-status-current-style ''
setw -g window-status-current-format '#[fg=#{theme_primary},bold] #I:#W#F #[default]'

setw -g window-status-style ''
setw -g window-status-format '#[fg=#{theme_fg_dim}] #I:#W#F '

setw -g window-status-bell-style 'fg=#{theme_warning},bold'

# messages
set -g message-style 'fg=#{theme_fg},bg=#{theme_bg_dim},bold'
