# vim:ft=tmux

theme_bg='default'
theme_bg_dim='colour8'
theme_fg='default'
theme_fg_dim='colour7'
theme_primary='colour4'
theme_accent='colour6'
theme_warning='colour3'
theme_error='colour1'
theme_success='colour2'
